// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwnzqvojgdoxiaiycyiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3bnpxdm9qZ2RveGlhaXljeWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNzU1MDMsImV4cCI6MjA1Nzc1MTUwM30.r1VpjxsC5V7iTmDWv7imemMWPi07QMZmjMhKeIDcAEg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);